from __future__ import annotations

from collections import defaultdict
from collections.abc import Iterable
from urllib.parse import urlparse

from app.schemas.job import JobProfile
from app.schemas.report import ApplicationReport, TailoredBullet
from app.schemas.resume import CandidateProfile, ResumeFact, ResumeProfile, ResumeSkill

MAX_SUMMARY_FACTS = 2
MAX_TAILORED_BULLETS = 5
MAX_EXPERIENCE_FACTS = 7
MAX_PROJECT_FACTS = 6

SECTION_LABELS = {
    "programming_language": "Languages",
    "backend_framework": "Backend",
    "frontend_framework": "Frontend",
    "database": "Databases",
    "cloud_devops": "DevOps/Tools",
    "ai_ml": "AI/ML",
    "data_tool": "Data Tools",
    "testing": "Testing",
    "security": "Security",
    "soft_skill": "Soft Skills",
    "domain": "Domain",
    "other": "Other",
}

LATEX_SPECIAL_CHARS = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}

RESUME_LATEX_TEMPLATE = r"""%-------------------------
% Resume in LaTeX
% Generated by ResumePilot from evidence-backed resume facts
% Based on Aditya Chaudhari's one-page ATS-optimized technical resume template
%-------------------------

\documentclass[letterpaper,10pt]{article}

\usepackage[empty]{fullpage}
\usepackage{titlesec}
\usepackage[usenames,dvipsnames]{color}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage{fancyhdr}
\usepackage[english]{babel}
\usepackage{iftex}
\ifPDFTeX
  \input{glyphtounicode}
  \pdfgentounicode=1
\fi

\pagestyle{fancy}
\fancyhf{}
\fancyfoot{}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}

\addtolength{\oddsidemargin}{-0.62in}
\addtolength{\evensidemargin}{-0.62in}
\addtolength{\textwidth}{1.24in}
\addtolength{\topmargin}{-0.74in}
\addtolength{\textheight}{1.48in}

\urlstyle{same}
\raggedbottom
\raggedright
\setlength{\parindent}{0pt}
\setlength{\tabcolsep}{0pt}

\titleformat{\section}{
  \vspace{-2pt}\scshape\raggedright\large\bfseries
}{}{0em}{}[\color{black}\titlerule \vspace{-1pt}]

\newcommand{\resumeItem}[1]{\item\small{#1}}
\newcommand{\resumeItemListStart}{%
  \begin{itemize}[leftmargin=0.17in, itemsep=0.8pt, topsep=1.5pt,%
    parsep=0pt, partopsep=0pt]%
}
\newcommand{\resumeItemListEnd}{\end{itemize}\vspace{2pt}}
\newcommand{\resumeRole}[4]{
  \vspace{2pt}
  \textbf{#1} \hfill \textbf{\small #2}\\
  \textit{\small #3} \hfill \textit{\small #4}\vspace{-2pt}
}
\newcommand{\resumeProject}[3]{
  \vspace{2pt}
  \textbf{#1} $|$ \emph{\small #2} $|$ \textbf{\small #3}\vspace{-2pt}
}

\renewcommand\labelitemi{$\vcenter{\hbox{\tiny$\bullet$}}$}

\begin{document}

<<HEADER>>
<<SUMMARY_SECTION>>
<<SKILLS_SECTION>>
<<TAILORED_SECTION>>
<<EXPERIENCE_SECTION>>
<<PROJECTS_SECTION>>
<<EDUCATION_SECTION>>
<<CERTIFICATIONS_SECTION>>

\end{document}
"""


def render_tailored_resume_latex(
    *,
    report: ApplicationReport,
    resume: ResumeProfile,
    job: JobProfile,
) -> str:
    """Render an evidence-backed tailored resume as LaTeX."""

    replacements = {
        "<<HEADER>>": _render_header(resume.candidate),
        "<<SUMMARY_SECTION>>": _render_summary_section(resume, report, job),
        "<<SKILLS_SECTION>>": _render_skills_section(resume.skills, report),
        "<<TAILORED_SECTION>>": _render_tailored_section(report.tailored_bullets),
        "<<EXPERIENCE_SECTION>>": _render_fact_section(
            title="Professional Experience",
            facts=resume.experience,
            max_items=MAX_EXPERIENCE_FACTS,
        ),
        "<<PROJECTS_SECTION>>": _render_fact_section(
            title="Projects",
            facts=resume.projects,
            max_items=MAX_PROJECT_FACTS,
        ),
        "<<EDUCATION_SECTION>>": _render_plain_fact_section("Education", resume.education),
        "<<CERTIFICATIONS_SECTION>>": _render_plain_fact_section(
            "Certifications", resume.certifications
        ),
    }
    rendered = RESUME_LATEX_TEMPLATE
    for marker, value in replacements.items():
        rendered = rendered.replace(marker, value)
    return rendered.strip() + "\n"


def escape_latex_text(value: str) -> str:
    return "".join(LATEX_SPECIAL_CHARS.get(char, char) for char in value)


def _render_header(candidate: CandidateProfile) -> str:
    name = escape_latex_text(candidate.name or "Candidate")
    contact_items = _contact_items(candidate)
    contact_lines = _chunked(contact_items, size=3)
    rendered_lines = [
        r"\begin{center}",
        rf"    {{\Huge \scshape {name}}} \\ \vspace{{2pt}}",
    ]
    for line in contact_lines:
        rendered_lines.append(rf"    \small {' $|$ '.join(line)} \\")
    if rendered_lines[-1].endswith(r" \\"):
        rendered_lines[-1] = rendered_lines[-1][:-3]
    rendered_lines.extend([r"\end{center}", r"\vspace{-10pt}"])
    return "\n".join(rendered_lines)


def _contact_items(candidate: CandidateProfile) -> list[str]:
    items: list[str] = []
    if candidate.location:
        items.append(escape_latex_text(candidate.location))
    if candidate.phone:
        normalized_phone = "".join(
            char for char in candidate.phone if char.isdigit() or char == "+"
        )
        items.append(_href(f"tel:{normalized_phone}", candidate.phone))
    if candidate.email:
        email = str(candidate.email)
        items.append(_href(f"mailto:{email}", email))
    for link in candidate.links:
        link_text = str(link).rstrip("/")
        items.append(_href(link_text, _display_url(link_text)))
    return items


def _render_summary_section(
    resume: ResumeProfile,
    report: ApplicationReport,
    job: JobProfile,
) -> str:
    summary_facts = [
        fact.text for fact in resume.facts if fact.section == "summary" and fact.text.strip()
    ][:MAX_SUMMARY_FACTS]
    if summary_facts:
        summary = " ".join(summary_facts)
    else:
        top_matches = [skill.skill for skill in report.matched_skills[:4]]
        role_context = _role_context(job)
        if top_matches:
            summary = (
                f"Evidence-backed technical resume tailored for {role_context}, "
                f"with supported experience in {_human_list(top_matches)}."
            )
        else:
            summary = f"Evidence-backed technical resume tailored for {role_context}."
    return _render_small_paragraph_section("Professional Summary", summary)


def _render_skills_section(skills: list[ResumeSkill], report: ApplicationReport) -> str:
    evidence_backed_skills = [skill for skill in skills if skill.evidence_ids]
    if not evidence_backed_skills:
        return ""

    matched_names = {_normalize_skill(skill.skill) for skill in report.matched_skills}
    grouped: dict[str, list[ResumeSkill]] = defaultdict(list)
    for skill in sorted(
        evidence_backed_skills,
        key=lambda item: (_normalize_skill(item.name) not in matched_names, item.name.lower()),
    ):
        grouped[skill.category.value].append(skill)

    lines = [r"\section{Technical Skills}", r"\small{"]
    for category, label in SECTION_LABELS.items():
        category_skills = grouped.get(category, [])
        if not category_skills:
            continue
        skill_names = ", ".join(escape_latex_text(skill.name) for skill in category_skills)
        lines.append(rf"\textbf{{{label}:}} {skill_names} \\")
    if lines[-1].endswith(r" \\"):
        lines[-1] = lines[-1][:-3]
    lines.extend([r"}", r"\vspace{0pt}"])
    return "\n".join(lines)


def _render_tailored_section(bullets: list[TailoredBullet]) -> str:
    safe_bullets = [
        bullet.bullet for bullet in bullets if bullet.evidence_ids and not bullet.unsupported_claims
    ][:MAX_TAILORED_BULLETS]
    return _render_bullet_section("Evidence-Backed Tailored Highlights", safe_bullets)


def _render_fact_section(*, title: str, facts: list[ResumeFact], max_items: int) -> str:
    return _render_bullet_section(title, [fact.text for fact in facts[:max_items]])


def _render_plain_fact_section(title: str, facts: list[ResumeFact]) -> str:
    if not facts:
        return ""
    escaped_lines = [escape_latex_text(fact.text) for fact in facts]
    return "\n".join(
        [
            rf"\section{{{title}}}",
            r"\small{",
            r" \\ ".join(escaped_lines),
            r"}",
            r"\vspace{-1pt}",
        ]
    )


def _render_small_paragraph_section(title: str, body: str) -> str:
    if not body.strip():
        return ""
    return "\n".join(
        [
            rf"\section{{{title}}}",
            rf"\small{{{escape_latex_text(body)}}}",
            r"\vspace{0pt}",
        ]
    )


def _render_bullet_section(title: str, bullets: Iterable[str]) -> str:
    clean_bullets = [bullet.strip() for bullet in bullets if bullet.strip()]
    if not clean_bullets:
        return ""
    lines = [rf"\section{{{title}}}", r"\resumeItemListStart"]
    lines.extend(rf"  \resumeItem{{{escape_latex_text(bullet)}}}" for bullet in clean_bullets)
    lines.append(r"\resumeItemListEnd")
    return "\n".join(lines)


def _href(target: str, label: str) -> str:
    return rf"\href{{{_escape_href_target(target)}}}{{{escape_latex_text(label)}}}"


def _escape_href_target(target: str) -> str:
    return (
        target.strip()
        .replace("\\", "")
        .replace("{", "%7B")
        .replace("}", "%7D")
        .replace("%", r"\%")
        .replace("#", r"\#")
        .replace("&", r"\&")
        .replace("_", r"\_")
    )


def _display_url(value: str) -> str:
    parsed = urlparse(value)
    if parsed.netloc:
        return f"{parsed.netloc}{parsed.path}".rstrip("/")
    return value


def _role_context(job: JobProfile) -> str:
    role = job.role_title or "the target role"
    if job.company:
        return f"{role} at {job.company}"
    return role


def _human_list(values: list[str]) -> str:
    if not values:
        return "relevant evidence-backed skills"
    if len(values) == 1:
        return values[0]
    return f"{', '.join(values[:-1])}, and {values[-1]}"


def _normalize_skill(value: str) -> str:
    return " ".join(value.casefold().split())


def _chunked(items: list[str], *, size: int) -> list[list[str]]:
    return [items[index : index + size] for index in range(0, len(items), size)]
